_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  advancedqueue: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_visibility_conditions: 0
  block_visibility_conditions_node: 0
  block_visibility_conditions_taxonomy: 0
  bootstrap_basic_image_gallery: 0
  bootstrap_layout_builder: 0
  bootstrap_styles: 0
  breakpoint: 0
  ckeditor5: 0
  color: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_demo: 0
  commerce_dps: 0
  commerce_file: 0
  commerce_kickstart_core: 0
  commerce_kickstart_layout_builder: 0
  commerce_kickstart_license: 0
  commerce_kickstart_media_product: 0
  commerce_kickstart_physical_product: 0
  commerce_kickstart_product: 0
  commerce_kickstart_search_api_catalog: 0
  commerce_kickstart_shipping: 0
  commerce_kickstart_site: 0
  commerce_license: 0
  commerce_log: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_payment_example: 0
  commerce_price: 0
  commerce_product: 0
  commerce_product_tax: 0
  commerce_promotion: 0
  commerce_shipping: 0
  commerce_store: 0
  commerce_tax: 0
  config: 0
  config_rewrite: 0
  config_split: 0
  contextual: 0
  core_views_facets: 0
  datetime: 0
  dblog: 0
  default_content: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  facets: 0
  facets_pretty_paths: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  image_delta_formatter: 0
  inline_block_title_automatic: 0
  inline_entity_form: 0
  interval: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  layout_builder: 0
  layout_builder_blocks: 0
  layout_builder_lock: 0
  layout_builder_modal: 0
  layout_builder_operation_link: 0
  layout_builder_restrictions: 0
  layout_builder_restrictions_by_region: 0
  layout_discovery: 0
  link: 0
  mailer_transport: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  media_library_theme_reset: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  physical: 0
  profile: 0
  search_api: 0
  search_api_db: 0
  section_library: 0
  shortcut: 0
  state_machine: 0
  symfony_mailer: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  pathauto: 1
  views: 10
  commerce_kickstart: 1000
theme:
  belgrade: 0
  claro: 0
  centarro_claro: 0
profile: commerce_kickstart
