_core:
  default_config_hash: HlN7eAN2N4JIHsYv56V4E7sqC9bS609KwvGFjyD_mgk
langcode: en
uuid: cce0d4c4-be79-4790-8ae2-0b0c00fa382e
name: 'Commerce Demo'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /frontpage
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
