_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 553ec0a1-9c7f-4fb0-a371-b96a02fa14e7
name: 'Drush Site-Install'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /frontpage
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
